# Generated by Django 3.0 on 2019-12-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_telecode', models.CharField(max_length=100)),
                ('station_abbr', models.CharField(max_length=100)),
                ('station_no', models.IntegerField()),
                ('ch_pinyin', models.CharField(max_length=100)),
                ('simp_pinyin', models.CharField(max_length=100)),
                ('origin_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_train_code', models.CharField(max_length=100)),
                ('train_no', models.CharField(max_length=100)),
                ('train_type', models.CharField(max_length=10)),
                ('train_sn', models.CharField(max_length=100)),
                ('from_station', models.CharField(max_length=100)),
                ('to_station', models.CharField(max_length=100)),
                ('between_station', models.CharField(max_length=100)),
            ],
        ),
    ]
