# Generated by Django 3.0 on 2020-01-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_telecode', models.CharField(max_length=100)),
                ('station_abbr', models.CharField(max_length=100)),
                ('station_no', models.IntegerField()),
                ('ch_pinyin', models.CharField(max_length=100)),
                ('simp_pinyin', models.CharField(max_length=100)),
                ('origin_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ToStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_telecode', models.CharField(max_length=100)),
                ('station_abbr', models.CharField(max_length=100)),
                ('station_no', models.IntegerField()),
                ('ch_pinyin', models.CharField(max_length=100)),
                ('simp_pinyin', models.CharField(max_length=100)),
                ('origin_info', models.CharField(max_length=200)),
            ],
        ),
    ]
