# Generated by Django 3.0 on 2020-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_fromstation_tostation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fromstation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tostation',
            name='id',
        ),
        migrations.AlterField(
            model_name='fromstation',
            name='station_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tostation',
            name='station_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
